### ISSUE TITLE
Ribbons module

### ISSUE THREAD

**Issue by romanlesnikov** [unacms/UNA#1617]

**Comment by MicroGeniusOS** [comment]
Ribbons module affter  installation am getting error and whole site crash 
Fatal error: Uncaught Error: Call to undefined method BxRibbonsConfig::getHtmlIds() in /opt/lampp/htdocs/modules/base/text/classes/BxBaseModTextTemplate.php:29 Stack trace: #0 /opt/lampp/htdocs/inc/classes/BxDolModuleProxy.php(49): BxBaseModTextTemplate->getJsCode('ribbons') #1 /opt/lampp/htdocs/modules/boonex/ribbons/classes/BxRibbonsModule.php(66): BxDolModuleProxy->__call('getJsCode', Array) #2 /opt/lampp/htdocs/inc/classes/BxDolRequest.php(97): BxRibbonsModule->serviceIncludeJs() #3 /opt/lampp/htdocs/inc/classes/BxDolRequest.php(57): BxDolRequest::_perform(Array, 'BxRibbonsModule', 'serviceIncludeJ...', Array, false) #4 /opt/lampp/htdocs/inc/classes/BxDolService.php(59): BxDolRequest::processAsService(Array, 'serviceIncludeJ...', Array, 'Module') #5 /opt/lampp/htdocs/inc/classes/BxDolService.php(89): BxDolService::call('bx_ribbons', 'include_js', Array, 'Module', false) #6 /opt/lampp/htdocs/inc/classes/BxDolTemplate.php(2765): BxDolService::callSerialized('a:2:{s:6:"modul...') #7 /opt/lampp/htdocs/cache/bx_templ_en_de in /opt/lampp/htdocs/modules/base/text/classes/BxBaseModTextTemplate.php on line 29
