### ISSUE TITLE
PHP error when invitation is requested

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#2554]
```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getModule() on boolean in /home/onlineme/public_html/modules/boonex/notifications/classes/BxNtfsResponse.php:286
Stack trace:
#0 /home/onlineme/public_html/modules/boonex/notifications/classes/BxNtfsResponse.php(51): BxNtfsResponse-&gt;sendNotifications(6032, Object(BxDolAlerts), Array)
#1 /home/onlineme/public_html/inc/classes/BxDolAlerts.php(119): BxNtfsResponse-&gt;response(Object(BxDolAlerts))
#2 /home/onlineme/public_html/inc/utils.inc.php(1370): BxDolAlerts-&gt;alert()
#3 /home/onlineme/public_html/modules/boonex/invites/classes/BxInvModule.php(490): bx_alert('bx_invites', 'request_notify', 1212, 0, Array)
#4 /home/onlineme/public_html/modules/boonex/invites/classes/BxInvTemplate.php(154): BxInvModule-&gt;onRequest(1212)
#5 /home/onlineme/public_html/inc/classes/BxDolModuleProxy.php(49): BxInvTemplate-&gt;getBlockFormRequest()
#6 /home/onlineme/public_html/modules/boonex/invites/classes/BxInvModule.php(189): BxDolModuleProxy-&gt;__call('getBlockFormReq...', Array)
#7 /home/online in <b>/home/onlineme/public_html/modules/boonex/notifications/classes/BxNtfsResponse.php</b> on line <b>286</b><br />
```

![image](https://user-images.githubusercontent.com/3324866/72481291-25bd7800-384e-11ea-8315-0758ba919f2a.png)

**Comment by romanlesnikov** [comment]
already fixed in https://github.com/unaio/una/issues/2107
