### ISSUE TITLE
Location field error

### ISSUE THREAD

**Issue by AlexTr** [unacms/UNA#3273]
- [x] Change "None" to "Please select..." in location field country selector
- [ ] PHP error when setting location field as location radius on search form
![4e0c3](https://user-images.githubusercontent.com/3324866/111970460-6948fb80-8b4f-11eb-8e61-c2531a20fe42.png)
```
PHP Fatal error: Uncaught Error: Call to protected method BxDolLocationField::getLocationVal() from context 'BxBaseFormView' in /var/www/.../template/scripts/BxBaseFormView.php:1743\nStack trace:\n
#0 /var/www/.../template/scripts/BxBaseSearchExtendedForm.php(178): BxBaseFormView->getLocationVal(Array, 'rad')\n
#1 /var/www/.../template/scripts/BxBaseSearchExtendedForm.php(152): BxBaseSearchExtendedForm->genInputLocationRadius(Array)\n
#2 /var/www/.../template/scripts/BxBaseFormView.php(812): BxBaseSearchExtendedForm->genInput(Array)\n
#3 /var/www/.../template/scripts/BxBaseFormView.php(543): BxBaseFormView->genRowStandard(Array)\n
#4 /var/www/.../template/scripts/BxBaseFormView.php(485): BxBaseFormView->genRow(Array)\n
#5 /var/www/.../template/scripts/BxBaseFormView.php(354): BxBaseFormView->genRows()\n
#6 /var/www/.../template/scripts/BxBaseFormView.php(310): BxBaseFormView->genForm()\n
#7 /var/www/.../template/scripts/BxBaseSearchExtended.php(56): BxBaseFormView->getCode()\n
#8 /var/www/.../template/scr in /var/www/.../template/scripts/BxBaseFormView.php on line 1743, 
referer: https://sitename/page/persons-home
```

**Comment by AntonLV** [comment]
PHP error was fixed in Ticket #3280
