### ISSUE TITLE
Studio: JS error in the Dashboard->Cache diagrams

### ISSUE THREAD

**Issue by LeonidSokushev** [unacms/UNA#3822]
With the following syntax:

_Uncaught (in promise) Error: Type mismatch. Value [object Object] does not match type number in column index 1
  at gvjs_yk ([www.gstatic.com/charts/51/js/jsapi_compiled_default_module.js:277:264)](http://www.gstatic.com/charts/51/js/jsapi_compiled_default_module.js:277:264))
  at gvjs_M.gvjs_.G_ ([www.gstatic.com/charts/51/js/jsapi_compiled_default_module.js:294:194)](http://www.gstatic.com/charts/51/js/jsapi_compiled_default_module.js:294:194))
  at gvjs_M.gvjs_.Yn ([www.gstatic.com/charts/51/js/jsapi_compiled_default_module.js:295:73)](http://www.gstatic.com/charts/51/js/jsapi_compiled_default_module.js:295:73))
  at BxDolStudioDashboard.showChart (gzip_loader.php:136:29)
  at callback (gzip_loader.php:135:287)
  at jsapi:156:59_

As the result the block isn't drawn

**Comment by AntonLV** [comment]
Fixed here #3827
